### ISSUE TITLE
404 on Sign up with Google

### ISSUE THREAD

**Issue by leowilkin** [JesseOgunlaja/Task-Tracker-Next-JS#6]
![Screenshot 2023-08-20 at 13 44 54](https://github.com/JesseOgunlaja/Task-Tracker-Next-JS/assets/64415791/b6f97f30-16d7-4f94-8931-0eae237f100e)

LKW

Link (https://taskmasterapp.com/dashboard)

**Comment by leowilkin** [comment]
Can be remedied by going back to homepage, which redirects to logged in screen. Only issue is bearer token is not valid on Projects page.

**Comment by JesseOgunlaja** [comment]
Hi Leo,

The reason you're encountering a 404 error when locating to the /dashboard
route is because I have deleted that page and replaced it with a
projects page.

The error with the projects page isn't to do with your token, it's an
annoying type error which I've fixed now.

I had a look at your GitHub. I didn't know you used Astro, what's it like?

Best WIshes,
Jesse.

**Comment by JesseOgunlaja** [comment]
Hi Leo,

Again. I was just wondering, did you navigate to any random pages on my
website such as /test and /shop.

I just looked at my Vercel logs and it showed requests going to these pages.

Best Wishes,
Jesse.

**Comment by JesseOgunlaja** [comment]
Log out and log back in

**Comment by leowilkin** [comment]
Lovely, thanks.
